name: Deploy to cloudrun

on:
  workflow_dispatch:
  push:
    branches:
      - measure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Navigate to folder
        run: cd baby_measurement

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: |
          cd baby_measurement
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/measure:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/measure:$GITHUB_SHA

      - name: Push to Google Container Registry
        run: |
          gcloud --quiet auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/measure:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy measure \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/measure:$GITHUB_SHA \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 1Gi\
            --min-instances=1\
            --timeout=900\
            --cpu 2